// let a = 88
// let b = "deepshikha"
// let c = true
// let d ="77"

// let a = true //can"t redeclare as it"s already declared above

//  let class1 : number
// class1 = 27 
// class ="veeni" //error as predefined

// programme 1
// function addi (g:number,h:number):number/*/coz we want get number as return "void"can use if didn"t want same/*/{
// return g+h
// }
// // console.log(addi(30,20))
// addi('20','10') //error


//string
let tiger :string = "lion"
tiger = "animal"
// tiger = 89

//boolean
let student:boolean
student =true
// student =34 //error

//number
let kilo :number
kilo =100
// kilo =false //error

//object
// here it"ll automatically get the type 

let dance ={
    Intrest:"mix",
    Types:"all",
    Forms:2
}

// here we"ll be giving the type 
  
let Dance:{Intrest:string,Types:string,Forms:number} = {

    Intrest:"mix",
    Types:"all",
    Forms:2 
}


let peekaboo :{rhymes:boolean,associated:string} = {
    rhymes:true,
    associated:"children"
}
